Fixed issue in migration files that caused the :offerings to not be created
Error:
Could not dump table "offerings" because of following NoMethodError
undefined method `[]' for nil:NilClass